### ISSUE TITLE
Implement event matching

### ISSUE THREAD

**Issue by CptMalfunction** [boons605/MotoGymkhanaRaceTiming#12]
The system is going to track the state of the race by events coming in from the timing and rider id units. This means we will have to match timing events to rider id events to be able to couple lap times to riders and to detect when riders leave the track without hitting the end gate.

A race has 4 primitive events:
- start rider id (when a rider is picked up in the start box)
- start timing event (when a rider triggers the timer at the start box)
- end rider id
- end timer

A race has 3 derived events:
- Lap end (when we have matching end events)
- Finish (when we have a matching set of the 4 primitives)
- DNF (when we have matches for the start events, but no ending events)

A rider has 3 possible states:
- Waiting for start (when we have a start rider id event)
- On track (we have a start rider id and a start timer)
- Off track (we have a finish or DNF event for the rider)
-- Off track means our system has stopped keeping track, a rider may enter the start box to be 'Waiting' again

We assume these things about the primitive events:
- start rider id always happens before start timing. Since the rider must calmly enter the start box in a race
- matching end id and timer events may happen in either order (if the id range is much bigger than the stop box)
- matching end id and timer events happen at most 10 seconds apart
- there will be no end id events for riders not currently on track (we can notify the unit on which ids to report when riders start)
- there will be no start id events for riders who are not lining up for the start box (tell riders to keep a safe distance)

The algorithm for keeping track of riders will be:

On start rider id event:
Add a new Waiting rider to the queue

On start timer event:
Take the oldest Waiting rider from the queue, match to the new timer event.
Set rider to On track
if there is no waiting rider, disregard event

On end timer event:
Match to closest end id event (+/-10 secs at most)
if there is no match, store event
if there is a match, issue a new Lap end event

On end id event
Match to closest end timer event (+/-10 secs at most)
if there is no match, store event
if there is a match, issue a new Lap end event

On Lap end event:
Match to riders currently on track
If it matches to the oldest on track, Issue a Finish event
If it matches to a younger on track rider, issue Finish event for matched driver. Issue DNF events for all older on track drivers

This algorithm should be implement in RaceManagement. Covered by unit tests and it should be possible to run a simulated race from the CLI by providing an events list in txt form

**Comment by boons605** [comment]
As discussed on discord:

- Permission to start, rider ID unit should be able to control a traffic light for feedback to the rider. 
- Result display event to timing unit or generic display unit (separate interface? To allow display-only devices)
- Single sensor operation, for example for world courses, online EC, GP8 competitions.

**Comment by boons605** [comment]
What to do on a failure of the ID unit or timer unit communication?

On some events, we may be able to recover by restarting the communication, or restarting the application.
Should we store 'current' runs somewhere in order to facilitate sort of graceful restart?

**Comment by CptMalfunction** [comment]
Added events for rider ready to start and rider finished to allow for a simple 'ready' signal at start and time display at finish
