### ISSUE TITLE
Ensure only riders on track are known by the finish ID unit

### ISSUE THREAD

**Issue by boons605** [boons605/MotoGymkhanaRaceTiming#32]
* Remove riders that DNF
* Remove riders that have finished after they leave stop box
 * Add riders that have started

**Comment by CptMalfunction** [comment]
Upon closer inspection there are a bunch of things that still need to happen in race tracker.

- Add and remove riders from id units when appropriate
- React to riders leaving id unit range (for example remove a waiting rider when they leave id unit range)
