### ISSUE TITLE
Management through WebApi

### ISSUE THREAD

**Issue by CptMalfunction** [boons605/MotoGymkhanaRaceTiming#39]
We need some endpoints in the web api to be able to manage the running race.

Management endpoints:
-- POST /AddRiders: takes a json with a list of all riders that should be tracked by the system
-- DELETE /Rider: takes a rider id as a query param and stops tracking this rider for the current race
-- POST /Config: takes a json that specifies a full race config (id units and timing unit details). Clears the current race state and (re) starts the race with the new settings

**Comment by CptMalfunction** [comment]
I suggest we take out the /Lock endpoint from this ticket. We dont need it for the test and the code it would taker is quite unrelated to riders and config

**Comment by boons605** [comment]
That's fine, we can create a new issue for this.

**Comment by CptMalfunction** [comment]
ill add it
