### ISSUE TITLE
Figure out display options

### ISSUE THREAD

**Issue by boons605** [boons605/MotoGymkhanaRaceTiming#4]
Figure out which display options are best

- Large 7-segment (seems a costly option)
- LED Matrix
- E paper?

**Comment by I-am-not-a-number** [comment]
ePaper seems an interesting solution!

I was also thinking about building 7 segment displays with LED stripes ... but it seems a lot of effort and I don't have a 3D printer yet.

**Comment by boons605** [comment]
> 
> 
> ePaper seems an interesting solution!
> 
> I was also thinking about building 7 segment displays with LED stripes ... but it seems a lot of effort and I don't have a 3D printer yet.

I've looked at ePaper, and although it seems to be interesting, it is uncertain if the reaction times are low enough and more important: The price. The MAX7219 matrix display solution is almost free and easy to come by. Loads of these displays can be found on AliExpress.
