### ISSUE TITLE
Power supply options - Power bank

### ISSUE THREAD

**Issue by boons605** [boons605/MotoGymkhanaRaceTiming#7]
https://www.electronics-lab.com/project/5v-to-12v-step-up-dc-dc-converter/

**Comment by boons605** [comment]
https://www.eleccircuit.com/lm2577-5v-to-12v-dc-converter-step-up-voltage-regulator/#5V_to_12V_DC_Converter_step_up_Voltage_Regulator

**Comment by I-am-not-a-number** [comment]
Hi there,

I'm using an Arduino with an Optex Z2R-400N for a very similar project. The Optex seems to work fine with 9V and the Arduino does, too (the board has a voltage converter for input of 3,3/5 - 12V). The data line of NPN version of the Optex goes to GND, so there's no need to convert the signal down to mircocontroller level ...

Cheers :-)

**Comment by boons605** [comment]
Interesting option, the NPN sensor. That might save a few components.
On the other hand: The micorocontroller is protected from accidental wrong connections this way. Accidental 12V would blow it up. Accidental ground won't blow it up now.

I don't see the relevance of the 9V supply: Power banks are easy to come by, battery management is integrated and everyone can charge them. There does not seem to be an equally easy and generic solution for a 9V supply, except for batteries which might not have the greatest capacity to supply and LED display for a longer time.

Most sensors are specced from 10 to 30V. 12V is common enough to be able to use anything that is easily sourceable in any country.

**Comment by I-am-not-a-number** [comment]
Thanks for your input!

I have not yet checked how long a 9V battery (that option would save me the power converter parts) would last. I guess it's not long, and I'll go for the power bank option as well.

The goal of my project is the same as yours ... I'm not doing Moto Gymkhana myself, but I'm building this for someone who does.

The timing issue remains to be solved, the milliseconds provided by my arduino (hardware) are off by about 0,04% (measured manually over a longer period of time) and the RTC (DS3231SN) only provides seconds. I thought of aligning "millis()" every seconds with the RTC, but I'm not sure this'll make the timing more accurate ;-)

**Comment by boons605** [comment]
I am using the DS3231 to count the seconds and then use a 100us timer based on the 8MHz crystal on the BluePill STM32 board. It helps :-)
You shouldn’t use millis() at all, since it doesn’t increase at 1000us intervals but at 1024us intervals and then compensates for that once every 42ms or so. 

The BluePill is cheaper and more powerful than any Arduino board. 

0.04% is 24ms over a minute. This solution has been tested to be equally accurate as our €2000,- professional race timing system. Measured with an oscilloscope (PicoScope 4444) it was off by max 80us compared to the simulated trigger. 

Anyway. You’re welcome to use my designs or contribute to this project too.
