### ISSUE TITLE
Adding penalties while racing

### ISSUE THREAD

**Issue by boons605** [boons605/MotoGymkhanaRaceTiming#79]
Als wedstrijdleider wil ik tijdens het rijden strafpunten kunnen invoeren, zodat het resultaat direct de strafpunten bevat

Als wedstrijdleider wil ik kort na het finishen strafpunten kunnen invoeren, omdat mensen doorschieten in het stopvak of op andere wijze strafpunten kunnen verdienen

**Comment by CptMalfunction** [comment]
Het is al mogelijk om:

- DNF te geven via POST /DNF
- DSQ te geven via POST /DSQ
- Strafseconden te geven via Post /Penalty

Al deze penalties worden teogepast op de huidige lap van de rider als deze nu aan het rijden is, of op het meest recente gereden lap. Daar hoeft de ui geen keuze in te maken. Als de endpoints aangeroepen worden tijden een lap dan komt de penalty op dat lap anders komen de penalties op het meest recente lap

Als een lap afgerond is dan kunnen de panelties in het lap object uitgelezen worden uit GET /Laps of GET /BestLapsByRider.

Wat er nog ontbreekt is een endpoint om de penalties uit te lezen die op het huidige lap toegepast worden terwijl dat lap nog bezig is. Dat ga ik maken voor deze issue

**Comment by CptMalfunction** [comment]
Nieuw endpoint:

- GET /Penalties
- Geeft alle openstaande penalties terug voor rijders die nu aan een lap bezig zijn.
- Output: ```{
    "0694d10b-3cc4-424b-823a-2b45b1b3455f": [
        {
            "reason": "",
            "seconds": 1,
            "staffName": "UI",
            "time": "2023-11-19T15:44:03.7680777+01:00",
            "eventId": "5b148b1b-c83c-4238-9e12-fab9d80a146c",
            "rider": {
                "name": "Test",
                "id": "0694d10b-3cc4-424b-823a-2b45b1b3455f"
            },
            "type": "PenaltyEvent"
        }
    ]
}```

Om het aantal seconden o[ te halen zou je zoiets doen als `penalties['rider guid'][0].seconds`

**Comment by rbf660** [comment]
Is het ook mogelijk om status van DSQ penalty toe te voegen?
