### ISSUE TITLE
StopEvents with no riders on track

### ISSUE THREAD

**Issue by rbf660** [boons605/MotoGymkhanaRaceTiming#84]
StopEvents that occur when there are no riders on track should be automically discarded. As these events do not make any sense. Also it causes risk that user selects an old StopEvent after a rider Finishes in StopBox, causing an eroneous result.

Alternative solution could be that the possibility is disabled in GUI to set the light in startbox to green until all stopEvents are cancelled. But this seems to create unnecessary tasks for user as there is no logical other option then discarding all stopEvents when there are no riders on track.

**Comment by CptMalfunction** [comment]
That seems reasonable. We should also have an endpoint to discard stop events that the users knows they will not be using
